--exid and muscid
/*
12 - BACK
13 - CHEST
14 - LEGS
15 - Abdominals
16 - SHOULDERS
17 - ARMS


*/

INSERT INTO MUSCLES_TRAINED VALUES(1,18);
INSERT INTO MUSCLES_TRAINED VALUES(2,10);
INSERT INTO MUSCLES_TRAINED VALUES(2,7);
INSERT INTO MUSCLES_TRAINED VALUES(2,8);
INSERT INTO MUSCLES_TRAINED VALUES(2,23);