INSERT INTO EXERCISES (ex_nm) VALUES ('Bench Press (Barbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Floor Bench Press (Barbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Incline Bench Press (Barbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Decline Bench Press (Barbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Bench Press (Dumbbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Floor Bench Press (Dumbbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Incline Bench Press (Dumbbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Decline Bench Press (Dumbbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Dips');
INSERT INTO EXERCISES (ex_nm) VALUES ('Overhead Press');
INSERT INTO EXERCISES (ex_nm) VALUES ('Overhead Press (Dumbbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Military Press');
INSERT INTO EXERCISES (ex_nm) VALUES ('Lateral Raises');
INSERT INTO EXERCISES (ex_nm) VALUES ('Front Raises');
INSERT INTO EXERCISES (ex_nm) VALUES ('Facepulls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Arnold Press');
INSERT INTO EXERCISES (ex_nm) VALUES ('Chest Press');
INSERT INTO EXERCISES (ex_nm) VALUES ('Chest Flys');
INSERT INTO EXERCISES (ex_nm) VALUES ('Chest Flys (Dumbbell)');
INSERT INTO EXERCISES (ex_nm) VALUES ('Shoulder External Rotation');
INSERT INTO EXERCISES (ex_nm) VALUES ('Push Ups');
INSERT INTO EXERCISES (ex_nm) VALUES ('Pull Ups');
INSERT INTO EXERCISES (ex_nm) VALUES ('Upright Rows');
INSERT INTO EXERCISES (ex_nm) VALUES ('Lat Pulldowns');
INSERT INTO EXERCISES (ex_nm) VALUES ('Rear Delt Flys');
INSERT INTO EXERCISES (ex_nm) VALUES ('Deadlifts');
INSERT INTO EXERCISES (ex_nm) VALUES ('Barbell Rows');
INSERT INTO EXERCISES (ex_nm) VALUES ('T Bar Rows');
INSERT INTO EXERCISES (ex_nm) VALUES ('Chest Supported Rows');
INSERT INTO EXERCISES (ex_nm) VALUES ('Cable Rows');
INSERT INTO EXERCISES (ex_nm) VALUES ('Meadow Rows');
INSERT INTO EXERCISES (ex_nm) VALUES ('Bicep Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Preacher Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Concentration Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Hammer Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Cheat Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Strict Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Incline Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Spider Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Gorilla Row');
INSERT INTO EXERCISES (ex_nm) VALUES ('Rope Hammer Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Tricep Pushdown');
INSERT INTO EXERCISES (ex_nm) VALUES ('Straight Arm Pulldown');
INSERT INTO EXERCISES (ex_nm) VALUES ('Overhead Tricep Extension');
INSERT INTO EXERCISES (ex_nm) VALUES ('Skullcrushers');
INSERT INTO EXERCISES (ex_nm) VALUES ('Close Grip Bench Press');
INSERT INTO EXERCISES (ex_nm) VALUES ('Kickbacks');
INSERT INTO EXERCISES (ex_nm) VALUES ('Squats');
INSERT INTO EXERCISES (ex_nm) VALUES ('Pistol Squats');
INSERT INTO EXERCISES (ex_nm) VALUES ('Leg Press');
INSERT INTO EXERCISES (ex_nm) VALUES ('Leg Extensions');
INSERT INTO EXERCISES (ex_nm) VALUES ('Glute Extensions');
INSERT INTO EXERCISES (ex_nm) VALUES ('Hip Thrusts');
INSERT INTO EXERCISES (ex_nm) VALUES ('Hack Squats');
INSERT INTO EXERCISES (ex_nm) VALUES ('Calf Raises');
INSERT INTO EXERCISES (ex_nm) VALUES ('Leg Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Pendulum Squats');
INSERT INTO EXERCISES (ex_nm) VALUES ('Cleans');
INSERT INTO EXERCISES (ex_nm) VALUES ('Adductor Machine');
INSERT INTO EXERCISES (ex_nm) VALUES ('Leg Raises');
INSERT INTO EXERCISES (ex_nm) VALUES ('Shrugs');
INSERT INTO EXERCISES (ex_nm) VALUES ('Lunges');
INSERT INTO EXERCISES (ex_nm) VALUES ('Merlin Squats');
INSERT INTO EXERCISES (ex_nm) VALUES ('Sissy Squats');
INSERT INTO EXERCISES (ex_nm) VALUES ('Russian Twists');
INSERT INTO EXERCISES (ex_nm) VALUES ('Crunches');
INSERT INTO EXERCISES (ex_nm) VALUES ('Sit Ups');
INSERT INTO EXERCISES (ex_nm) VALUES ('Planks');
INSERT INTO EXERCISES (ex_nm) VALUES ('Side Leg Raise');
INSERT INTO EXERCISES (ex_nm) VALUES ('Star Crunches');
INSERT INTO EXERCISES (ex_nm) VALUES ('Bicycle Crunches');
INSERT INTO EXERCISES (ex_nm) VALUES ('Wrist Curls');
INSERT INTO EXERCISES (ex_nm) VALUES ('Farmers Walks');
INSERT INTO EXERCISES (ex_nm) VALUES ('Dead Hangs');
INSERT INTO EXERCISES (ex_nm) VALUES ('Kettlebell Swings');


