
INSERT INTO EXERCISES (name) VALUES ('Bench Press (Barbell)');
INSERT INTO EXERCISES (name) VALUES ('Floor Bench Press (Barbell)');
INSERT INTO EXERCISES (name) VALUES ('Incline Bench Press (Barbell)');
INSERT INTO EXERCISES (name) VALUES ('Decline Bench Press (Barbell)');
INSERT INTO EXERCISES (name) VALUES ('Bench Press (Dumbbell)');
INSERT INTO EXERCISES (name) VALUES ('Floor Bench Press (Dumbbell)');
INSERT INTO EXERCISES (name) VALUES ('Incline Bench Press (Dumbbell)');
INSERT INTO EXERCISES (name) VALUES ('Decline Bench Press (Dumbbell)');
INSERT INTO EXERCISES (name) VALUES ('Dips');
INSERT INTO EXERCISES (name) VALUES ('Overhead Press');
INSERT INTO EXERCISES (name) VALUES ('Overhead Press (Dumbbell)');
INSERT INTO EXERCISES (name) VALUES ('Military Press');
INSERT INTO EXERCISES (name) VALUES ('Lateral Raises');
INSERT INTO EXERCISES (name) VALUES ('Front Raises');
INSERT INTO EXERCISES (name) VALUES ('Facepulls');
INSERT INTO EXERCISES (name) VALUES ('Arnold Press');
INSERT INTO EXERCISES (name) VALUES ('Chest Press');
INSERT INTO EXERCISES (name) VALUES ('Chest Flys');
INSERT INTO EXERCISES (name) VALUES ('Chest Flys (Dumbbell)');
INSERT INTO EXERCISES (name) VALUES ('Shoulder External Rotation');
INSERT INTO EXERCISES (name) VALUES ('Push Ups');
INSERT INTO EXERCISES (name) VALUES ('Pull Ups');
INSERT INTO EXERCISES (name) VALUES ('Upright Rows');
INSERT INTO EXERCISES (name) VALUES ('Lat Pulldowns');
INSERT INTO EXERCISES (name) VALUES ('Rear Delt Flys');
INSERT INTO EXERCISES (name) VALUES ('Deadlifts');
INSERT INTO EXERCISES (name) VALUES ('Barbell Rows');
INSERT INTO EXERCISES (name) VALUES ('T Bar Rows');
INSERT INTO EXERCISES (name) VALUES ('Chest Supported Rows');
INSERT INTO EXERCISES (name) VALUES ('Cable Rows');
INSERT INTO EXERCISES (name) VALUES ('Meadow Rows');
INSERT INTO EXERCISES (name) VALUES ('Bicep Curls');
INSERT INTO EXERCISES (name) VALUES ('Preacher Curls');
INSERT INTO EXERCISES (name) VALUES ('Concentration Curls');
INSERT INTO EXERCISES (name) VALUES ('Hammer Curls');
INSERT INTO EXERCISES (name) VALUES ('Cheat Curls');
INSERT INTO EXERCISES (name) VALUES ('Strict Curls');
INSERT INTO EXERCISES (name) VALUES ('Incline Curls');
INSERT INTO EXERCISES (name) VALUES ('Spider Curls');
INSERT INTO EXERCISES (name) VALUES ('Gorilla Row');
INSERT INTO EXERCISES (name) VALUES ('Rope Hammer Curls');
INSERT INTO EXERCISES (name) VALUES ('Tricep Pushdown');
INSERT INTO EXERCISES (name) VALUES ('Straight Arm Pulldown');
INSERT INTO EXERCISES (name) VALUES ('Overhead Tricep Extension');
INSERT INTO EXERCISES (name) VALUES ('Skullcrushers');
INSERT INTO EXERCISES (name) VALUES ('Close Grip Bench Press');
INSERT INTO EXERCISES (name) VALUES ('Kickbacks');
INSERT INTO EXERCISES (name) VALUES ('Squats');
INSERT INTO EXERCISES (name) VALUES ('Pistol Squats');
INSERT INTO EXERCISES (name) VALUES ('Leg Press');
INSERT INTO EXERCISES (name) VALUES ('Leg Extensions');
INSERT INTO EXERCISES (name) VALUES ('Glute Extensions');
INSERT INTO EXERCISES (name) VALUES ('Hip Thrusts');
INSERT INTO EXERCISES (name) VALUES ('Hack Squats');
INSERT INTO EXERCISES (name) VALUES ('Calf Raises');
INSERT INTO EXERCISES (name) VALUES ('Leg Curls');
INSERT INTO EXERCISES (name) VALUES ('Pendulum Squats');
INSERT INTO EXERCISES (name) VALUES ('Cleans');
INSERT INTO EXERCISES (name) VALUES ('Adductor Machine');
INSERT INTO EXERCISES (name) VALUES ('Leg Raises');
INSERT INTO EXERCISES (name) VALUES ('Shrugs');
INSERT INTO EXERCISES (name) VALUES ('Lunges');
INSERT INTO EXERCISES (name) VALUES ('Sissy Squats');
INSERT INTO EXERCISES (name) VALUES ('Russian Twists');
INSERT INTO EXERCISES (name) VALUES ('Crunches');
INSERT INTO EXERCISES (name) VALUES ('Sit Ups');
INSERT INTO EXERCISES (name) VALUES ('Planks');
INSERT INTO EXERCISES (name) VALUES ('Side Leg Raise');
INSERT INTO EXERCISES (name) VALUES ('Star Crunches');
INSERT INTO EXERCISES (name) VALUES ('Bicycle Crunches');
INSERT INTO EXERCISES (name) VALUES ('Wrist Curls');
INSERT INTO EXERCISES (name) VALUES ('Farmers Walks');
INSERT INTO EXERCISES (name) VALUES ('Dead Hangs');
INSERT INTO EXERCISES (name) VALUES ('Kettlebell Swings');


