INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Trapezius', 6);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Rhomboids', 6);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Latissimus Dorsi', 6);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Teres Major', 6);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Lower Back', 6);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Rear Deltoid', 10);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Pectoralis Major', 9);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Pectoralis Minor', 9);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Side Deltoid', 10);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Front Deltoid', 10);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Glutes', 7);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Hamstrings', 7);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Quadriceps', 7);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Adductors', 7);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Calves', 7);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Rectus Abdominis', 11);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Transversus Abdominis', 11);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Short Head (Biceps)', 8);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Long Head (Biceps)', 8);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Lateral Head (Triceps)', 8);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Medial Head (Triceps)', 8);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Long Head (Triceps)', 8);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Forearm', 8);
