INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Trapezius', 12);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Rhomboids', 12);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Latissimus Dorsi', 12);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Teres Major', 12);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Lower Back', 12);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Rear Deltoid', 16);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Pectoralis Major', 13);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Pectoralis Minor', 13);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Side Deltoid', 16);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Front Deltoid', 16);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Glutes', 14);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Hamstrings', 14);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Quadriceps', 14);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Adductors', 14);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Calves', 14);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Rectus Abdominis', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Transversus Abdominis', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Short Head (Biceps)', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Long Head (Biceps)', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Lateral Head (Triceps)', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Medial Head (Triceps)', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Long Head (Triceps)', 15);
INSERT INTO MUSCLES(musc_nm, musc_cat_id) VALUES('Forearm', 15);
