--SET UP TABLES
CREATE OR REPLACE TABLE USERS (
    pid int IDENTITY(1,1) PRIMARY KEY,
    f_name VARCHAR(255) NOT NULL,
    l_name VARCHAR(255) NOT NULL
);
CREATE OR REPLACE TABLE USER_WEIGHTS (
    wgt_id int IDENTITY(1,1) PRIMARY KEY,
    pid int NOT NULL FOREIGN KEY REFERENCES(USERS),
    weight_kg DOUBLE(100,2) NOT NULL,
    date NOT NULL
);

CREATE OR REPLACE TABLE FOOD_ITEMS (
    food_id int IDENTITY(1,1) PRIMARY KEY,
    food_nm VARCHAR(255),
    protein int,
    fats int,
    carbs int
);
CREATE OR REPLACE TABLE MENU_ITEMS (
    menu_id int NOT NULL FOREIGN KEY REFERENCES(FOOD_MENUS),
    food_id int NOT NULL FOREIGN KEY REFERENCES(FOOD_ITEMS)
);
CREATE OR REPLACE TABLE FOOD_MENUS (
    menu_id int IDENTITY(1,1) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    descript VARCHAR(255)
);
CREATE OR REPLACE TABLE EXERCISES (
    --TO BE WORKED ON
);
CREATE OR REPLACE TABLE USER_LIFTS_PR (
    --TO BE WORKED ON
);
CREATE OR REPLACE TABLE PROGRAMS (
    --TO BE WORKED ON
);
CREATE OR REPLACE TABLE MUSCLES (
    --TO BE WORKED ON
);
CREATE OR REPLACE TABLE CATEGORIES (
    cid int IDENTITY(1,1) PRIMARY KEY,
    cat_nm VARCHAR(255) NOT NULL,
    descript VARCHAR(255)
);
CREATE OR REPLACE TABLE FOOD_CATEGORIES (
    food_id int NOT NULL FOREIGN KEY REFERENCES(FOOD_ITEMS),
    cid int NOT NULL FOREIGN KEY REFERENCES(CATEGORIES)
);

